name: Test and Deploy
on:
  push:
    branches: [ '*' ]
    tags: [ '*' ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run automatically at 8AM PST Monday-Friday
    - cron: '0 15 * * 1-5'
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        node: [ 6, 7, 8, 10, lts/* ]
    env:
      version: ${{ matrix.node }}
    steps:
      - name: Checkout sendgrid-nodejs
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Reset env vars
        if: env.version == 'lts/*'
        run: echo "version=lts" >> "$GITHUB_ENV"

      - run: npm install
      - name: Run Tests
        run: make test-docker
